### ISSUE TITLE
Bug, player teleport to inside interior by looting.

### ISSUE THREAD

**Issue by jetpnix** [utkuali/pacificheist-ESX-#1]
Player can teleport accidentally or intentionally by spamming e directly above the loot location. I think it may have an issue with native GetDistanceBetweenCoords(). Here is the video of me attempting to do it.

Video link https://streamable.com/mrt0n

It is at 01:01 mark

Great script overall! Thanks!

**Comment by utkuali** [comment]
Starting from client.lua/line:1692 can you change local dst1 to GetDistanceBetweenCoords(coords, UTK.cash1.x, UTK.cash1.y, UTK.cash1.z, true)
and ofc apply it to the following ones, let's see if that works. Sorry, I can't test it myself, I don't have time these days.

**Comment by utkuali** [comment]
@jetpnix Can you try it out?

**Comment by jetpnix** [comment]
Ohh ill do i forgot, been busy debugging other mods

**Comment by jetpnix** [comment]
@utkuali Yeppp that fixed it! The z was not considered before, by enabling it, now it considers Z coordinate to.
