### ISSUE TITLE
Vault Door not opening | es_extended issue with coords in client.lua

### ISSUE THREAD

**Issue by Jailmate** [utkuali/pacificheist-ESX-#10]
After doing the second hacking, you can hear the door unlocking but the door doesnt actually open. get a client-side error in F8 saying 

SCRIPT ERROR: @es_extended/client/functions.lua:500: vector3(...) argument 1 had type nil
handler (@utk_ornateheist/client.lua:1272)
fn (@utk_ornateheist/client.lua:1480)

Line 1272 of client.lua is:
local obj = ESX.Game.GetClosestObject(UTK.vault.type, vector3(UTK.vault.x, UTK.vault.y, UTK.vault.z))

line 500 of function.lua is:
coords = vector3(coords.x, coords.y, coords.z)

**Comment by utkuali** [comment]
it has fixed with the latest commit https://github.com/utkuali/pacificheist-ESX-/commit/5b5d0c4a494a381fa41e353d3f17fc0bafe0620a
