### ISSUE TITLE
Heist Loud Doesn't Work.

### ISSUE THREAD

**Issue by NataIynn** [utkuali/pacificheist-ESX-#12]
The first step to starting Loud, doesn't work. The door doesn't unlock and the particles keep playing.

The silent heist works fine.

**Comment by Jamakasi777** [comment]
> The first step to starting Loud, doesn't work. The door doesn't unlock and the particles keep playing.
> 
> The silent heist works fine.
I have same problem

**Comment by NewWorldFin** [comment]
I have almost the same but the silent heist hangs after the first stage and the characters freeze in place.

**Comment by MattBrownn** [comment]
Mine doesn't play any effects, and the character just gets frozen on both silent and loud robbery types

**Comment by utkuali** [comment]
this is not an issue, you just don't know anything about fivem
you either don't have mythic_notify and progressBars, or they are not started, or they are not named correctly, or you have both and named correctly but you have old mythic_notify

**Comment by NataIynn** [comment]
I have everything new, and they are started correctly.

**Comment by MattBrownn** [comment]
Maybe if it was listed under dependencies like 90% of other scripts that require specific resources, people wouldn't have to jump in here asking questions. You fucking tool

**Comment by utkuali** [comment]
Maybe if you would read the README like 90% of other people did, you would have no issue using the script. The issue is you that does not understand how to install and run the script. Code is perfectly working. I'm a fucking tool whatever it means :DD
