### ISSUE TITLE
Loud Heist Broken

### ISSUE THREAD

**Issue by NataIynn** [utkuali/pacificheist-ESX-#13]
Silent Heist is completely working, but loud heist is broken. I have everything up-to-date, so don't go closing my issue when it's an issue. If you closing my issue, at-least post correct github links instead of invalid links.

ensure progressBars
ensure mythic_notify
ensure utk_ornateprops
ensure utk_ornateheist

**Comment by utkuali** [comment]
First of all, there are at least 100 servers using this script, working fine.
So script is not broken, it is something you do, or you don't.

And it's not my problem that the author of the mythic_notify decided to remove his repo.

**Comment by MattBrownn** [comment]
> Silent Heist is completely working, but loud heist is broken. I have everything up-to-date, so don't go closing my issue when it's an issue. If you closing my issue, at-least post correct github links instead of invalid links.
> 
> ensure progressBars
> ensure mythic_notify
> ensure utk_ornateprops
> ensure utk_ornateheist

If you wanna reach out to me, I can actually provide you with some support, I was able to fix all the ISSUES that I was running into. And yes, they are issues @utkuali , no matter how small or large, an issue is an issue. Learn to provide support for your scripts correctly and quit being an unprofessional shit stain.

**Comment by utkuali** [comment]
Talking about professionalism and insulting me, keep up!

**Comment by coverrt** [comment]
I can confirm it is broken, unfortunately.

https://f000.backblazeb2.com/file/covert/IMH6ugbegM.mp4

I can provide any additional details you need so it can hopefully get fixed.

**Comment by utkuali** [comment]
You don't have progressBars ffs, read the README !!!

**Comment by yagizher** [comment]
You guys are just stupid...

**Comment by yagizher** [comment]
Its not broken. Like 100 servers are using it.

**Comment by coverrt** [comment]
You're right, the _or_ threw me off when you were listing the dependencies so I looked over progressBars. Any reason it can't be in the manifest as a dependency so there is an error thrown if missing?

```
dependencies {
    'progressBars'
}
```
