### ISSUE TITLE
How can I add items to the database?

### ISSUE THREAD

**Issue by xXMrPotatoXx** [utkuali/pacificheist-ESX-#14]
I dowloaded  the pacificheist everything is working except the items i dont know how to add into my database please help.

**Comment by utkuali** [comment]
[weight.sql](https://github.com/utkuali/pacificheist-ESX-/blob/master/weight.sql)

**Comment by xXMrPotatoXx** [comment]
what should i do with it?

**Comment by xXMrPotatoXx** [comment]
I have weight.sql and item.sql but i dont  know were to put the code

**Comment by utkuali** [comment]
you insert it into your database

**Comment by xXMrPotatoXx** [comment]
I cant find my database.

**Comment by xXMrPotatoXx** [comment]
Were is it?
