### ISSUE TITLE
Ugly text. How can I fix it?

### ISSUE THREAD

**Issue by Achim-Sommer** [utkuali/pacificheist-ESX-#15]
The text that is displayed at the top of the game for example I don't have a lock pick. Is just black text without a box.
It is very difficult to read and you will quickly overlook it.

**Comment by utkuali** [comment]
It's not related to my scripts, it is related to mythic_notify you are using, you should look into that

**Comment by Achim-Sommer** [comment]
but in your other script it looks nicer

**Comment by yagizher** [comment]
its about mythic notify

**Comment by Chxttr** [comment]
@GermanGaming How it is notified can be changed using Exports, Looks around in the scripts and get used to them.

**Comment by utkuali** [comment]
> @GermanGaming How it is notified can be changed using Exports, Looks around in the scripts and get used to them.

thank you
