### ISSUE TITLE
pacificheist not working

### ISSUE THREAD

**Issue by xXMrPotatoXx** [utkuali/pacificheist-ESX-#16]
Pls help me heres a video of it 
https://drive.google.com/file/d/1T9ex4aaDHoOVMyQFAiNLQrjJ3mK-epGa/view?usp=sharing

**Comment by xXMrPotatoXx** [comment]
I have progressbar and pNotify and mythic notify

**Comment by Chxttr** [comment]
@xXMrPotatoXx The drive link is locked, Access is needed to view it

**Comment by xXMrPotatoXx** [comment]
https://drive.google.com/file/d/1T9ex4aaDHoOVMyQFAiNLQrjJ3mK-epGa/view?usp=drivesdk  

Heres the link it should work !

**Comment by Chxttr** [comment]
> https://drive.google.com/file/d/1T9ex4aaDHoOVMyQFAiNLQrjJ3mK-epGa/view?usp=drivesdk
> 
> Heres the link it should work !

Is there any F8 error that comes up after this event happens?
