### ISSUE TITLE
Stop grabbing

### ISSUE THREAD

**Issue by Dikidorus007** [utkuali/pacificheist-ESX-#17]
Hi, is it possible to have a button which stops the money grabbing, so you can take half of the money and then leave instead of waiting until the whole thing is empty?

**Comment by Chxttr** [comment]
@Dikidorus007 This is not an issue, If you wish that features were added, Join utku's discord and suggest it there!

https://discord.gg/yqHmvcr

**Comment by utkuali** [comment]
[git repo](https://github.com/utkuali/cash-cart-loot-test) it is possible, but I don't have time to work on this
