### ISSUE TITLE
Pacificheist not working!

### ISSUE THREAD

**Issue by xXMrPotatoXx** [utkuali/pacificheist-ESX-#18]
I did everything i insert everything to my database i have mythic_notify es_extended proggresbar and pNotify i dont know why its not working.

Heres a video of it 
https://drive.google.com/file/d/1T9ex4aaDHoOVMyQFAiNLQrjJ3mK-epGa/view?usp=sharing

**Comment by utkuali** [comment]
For the 15478558745474th time, you have a different mythic_notify, please go to utk_ornateheist/client.lua and change every SendAlert to DoHudText
