### ISSUE TITLE
When the pacific robbery started a police got a massage but it will apair only for 1 or 2 second how can i make it 5 or 6?

### ISSUE THREAD

**Issue by xXMrPotatoXx** [utkuali/pacificheist-ESX-#19]
?

**Comment by utkuali** [comment]
it stays for 10 seconds
https://github.com/utkuali/pacificheist-ESX-/blob/50c100808f0ebaa9ce73fbc548ef41ae95c2e384/%5BUTK%5D/utk_ornateheist/client.lua#L1506
