### ISSUE TITLE
Doors are not opening

### ISSUE THREAD

**Issue by ImJustASimpleMan** [utkuali/pacificheist-ESX-#2]
after placing thermal charge doors do not open and orange smoke stays until script is stopped

**Comment by utkuali** [comment]
mythic_notfiy issue, make sure to install it correctly and read README.md carefully

**Comment by ImJustASimpleMan** [comment]
orginal mythic notify got removed from github

**Comment by utkuali** [comment]
I will change it to pNotify soon

**Comment by ImJustASimpleMan** [comment]
can u send me mythic notify? i really need it get working today

**Comment by utkuali** [comment]
I can't do it without the author's permission, looks like he pulled the repo which means it is no longer public.

**Comment by ImJustASimpleMan** [comment]
welp looks like i will need to wait. thanks for replying

**Comment by ImJustASimpleMan** [comment]
well i got mythic notify from friend and it says No such export sendalert in resource mythic notify

**Comment by utkuali** [comment]
then it's the old version, either change every "SendAlert" to "DoHudText" or just use the pNotify version I just uploaded.

**Comment by ImJustASimpleMan** [comment]
New pnotify version got same error

**Comment by utkuali** [comment]
what is the error ??

**Comment by ImJustASimpleMan** [comment]
no such export sendalert in resource mythic notify

**Comment by ImJustASimpleMan** [comment]
i got pNotify enabled and mythic notify is disabled

**Comment by utkuali** [comment]
try again now

**Comment by utkuali** [comment]
and make you are using clientpNotify.lua instead of client.lua

**Comment by ImJustASimpleMan** [comment]
no error but doors are not opening

**Comment by ImJustASimpleMan** [comment]
and orange smoke from thermal charge

**Comment by ImJustASimpleMan** [comment]
so?

**Comment by utkuali** [comment]
Have you tried the latest clientpNotify.lua ?

**Comment by ImJustASimpleMan** [comment]
yep i did and i use latest version

**Comment by utkuali** [comment]
Well, try mythic_notify but in utk_ornateheist/client.lua change every SendAlert to DoHudText, that should work. You will need to edit my script not mythic_notify

**Comment by ImJustASimpleMan** [comment]
![](https://i.imgur.com/x9rq0bb.jpg)

**Comment by utkuali** [comment]
As I said, in utk_ornateheist/client.lua change every SendAlert to DoHudText

**Comment by ImJustASimpleMan** [comment]
i did that

**Comment by ImJustASimpleMan** [comment]
so

**Comment by utkuali** [comment]
No, you haven't. If you've done that you wouldn't get the error no such export "SendAlert"

**Comment by ImJustASimpleMan** [comment]
Notepad++ i replaced 32 SendAlerts

**Comment by ImJustASimpleMan** [comment]
its replaced i checked again

**Comment by utkuali** [comment]
I don't one but you will never get that error if you changed all the "SendAlert"s, it's just impossible.

**Comment by ImJustASimpleMan** [comment]
i can even send it to u

**Comment by utkuali** [comment]
okay send it to me

**Comment by ImJustASimpleMan** [comment]
[](http://www.mediafire.com/file/utjctv53q328s0j/utk_ornateheist.zip)

**Comment by ImJustASimpleMan** [comment]
http://www.mediafire.com/file/utjctv53q328s0j/utk_ornateheist.zip

**Comment by utkuali** [comment]
Yes, it is correct. Clear cache, restart everything I have no idea. Very weird error.

**Comment by ImJustASimpleMan** [comment]
no error. Doors are opening on other players screen but cant continue heist

**Comment by ImJustASimpleMan** [comment]
When i place charge doors are not opening for me and smoke comes out

**Comment by utkuali** [comment]
I need more info about that issues.

**Comment by ImJustASimpleMan** [comment]
i think that mythic notify is needed

**Comment by ImJustASimpleMan** [comment]
but its not available

**Comment by Dracon837** [comment]
i got the same problem and im using pNotify
