### ISSUE TITLE
Error starting the rob

### ISSUE THREAD

**Issue by xBrunex** [utkuali/pacificheist-ESX-#21]
Hello

When i go to the first door it plant the thermal_charge charge the progressBar but don't open the door.
In F8 there is alot of mensages "script:progressbars:nui (alot of numbers from 0 to 101) @progressbars/h.html:44".

In the other door using a Lockpick give error in mythic_notify.

I have it working 100% with others scripts

**Comment by xBrunex** [comment]
In this door:
![image](https://user-images.githubusercontent.com/68948623/88833907-f27b7e80-d1ca-11ea-982b-7dda02115502.png)
This is when we use Lockpick in the first door and freeze the char, can't move and nothing.

In this door:
![image](https://user-images.githubusercontent.com/68948623/88833518-476ac500-d1ca-11ea-93c0-89b31d06b852.png)
Stay like this and no open the door...

**Comment by utkuali** [comment]
https://github.com/utkuali/pacificheist-ESX-/issues/18#issuecomment-646760143

**Comment by xBrunex** [comment]
**utkuali**
Thanks for reply

**"you have a different mythic_notify"**
Can you tell me what version of mythic_notify do you have config in your script ? Or can you share it to me ?

Thanks mate

**Comment by utkuali** [comment]
do what the comment says

**Comment by xBrunex** [comment]
Man i have changed every **:SendAlert** to **.DoHudText** and now I can enter in the first door by the lockpick but it never shows any notification from mythic.
I have found the id_card and tried to open the second door "the one hackeble inside". and nothing happens.


The other door to melt is not working now, no melt no nothing.

Here is the example from what I do every line: 
![image](https://user-images.githubusercontent.com/68948623/88837060-9a934680-d1cf-11ea-980f-c220f26a01cd.png)

**Comment by utkuali** [comment]
not .DoHudText, it must be :DoHudText why do you change the : to . no one said that

**Comment by xBrunex** [comment]
Okay mate you're right, now everything is working 100%

Maybe is better you update your README.md telling about this to the people about replace SendAlert for DoHudText if they have problems with it.

One question if possible; this rob has 2 options, the door with lockpick and the door with thermal pad.
Is it possible to disable the rob from the door lockpick and leave just the other way ?

Thanks for this script and very nice job mate, congratulations!
