### ISSUE TITLE
When I complete hack on hacker laptop the door does not open

### ISSUE THREAD

**Issue by Spraqo** [utkuali/pacificheist-ESX-#22]

**Comment by Spraqo** [comment]
Im getting no issues in the F8 Client or server log. Im not sure if its because of the Police door.

**Comment by Spraqo** [comment]
![image](https://user-images.githubusercontent.com/69029415/89005155-c8f94a80-d2d1-11ea-98e8-4fe1872cc7ae.png)

**Comment by utkuali** [comment]
in the image you are a police, police can't rob the bank instead they can just unlock/lock the doors

**Comment by Spraqo** [comment]
oh no its just the way my lock script is wrote that it shows for everyone I'm still writing it. It was because I had that door added in my lock script whilst you already had one in so I just removed that door from mine and everything seemed to work. Thanks anyways 👍
