### ISSUE TITLE
Time Frame

### ISSUE THREAD

**Issue by JustMeGaming** [utkuali/pacificheist-ESX-#23]
Is it possible to extend the robbery time?

**Comment by JustMeGaming** [comment]
Why close this case and not give an answer? I want to extend the seconds to enter the vault and leave.

**Comment by utkuali** [comment]
because you don't even look at the code, if you would you could easily see what to change to extend heist duration

**Comment by JustMeGaming** [comment]
I did look at the code, maybe it evaded my eyes?

**Comment by JustMeGaming** [comment]
assumptions are the death of us.

**Comment by utkuali** [comment]
> if you would you could easily see what to change to extend heist duration

**Comment by JustMeGaming** [comment]
obviously that isn't the case in this situation.

**Comment by JustMeGaming** [comment]
btw, that wasn't easy to find. I had to search for different commands to find it as most people would put something like that on the top in the config to easily change it. Next time, instead of being stuck up and assuming people don't look before asking, be helpful. You on the other hand like to be petty.

**Comment by Splati** [comment]
Hello, can somebody help me. I would like to have 110 seconds until the gas comes.

**Comment by MarDevelopment** [comment]
line 1331 in server.cfg UTK.vaulttime =

**Comment by Splati** [comment]
Thank you bro
