### ISSUE TITLE
no "explosion" after end of progressbar

### ISSUE THREAD

**Issue by ghost** [utkuali/pacificheist-ESX-#29]
Hello, 

I have no errors but at the end of the progress bar nothing happens, the animation of the charge is always present continuously

Sorry bad english

https://gyazo.com/34bb9d65067ba38511637eab6dcf7101

**Comment by utkuali** [comment]
https://github.com/utkuali/pacificheist-ESX-/issues/18#issuecomment-646760143

**Comment by ghost** [comment]
Allready done

**Comment by ghost** [comment]
https://paste-me.net/duguc

**Comment by ghost** [comment]
can you help me ?
