### ISSUE TITLE
Hello guys, I’m Alex, i have big problem laptop not work!

### ISSUE THREAD

**Issue by MindOnFire93** [utkuali/pacificheist-ESX-#35]
Hello guys, I’m Alex, i have big problem, i try to roll back the project when i secure this script work normally, but nothing, is all the same, database, version, server, all the same , but the problem is when i cklick on bruteforce icon in the hakcking laptop, or in connector, nothing is opened… no errors nothing, other way with card work normally, but i really can’t understand where is the problem, try to roll back the ctx version to the default one, when all work fine, but nithing… I can only think that the problem is on the client or gta side, that it doesn’t work with the new version, I don’t know, 2 months ago everything worked, and today with the same versions, on the server side the hacking part doesn’t work, to someone else did this problem happen? Please help me, thank you, Cheers

**Comment by nurrifqialhusaini** [comment]
Me too, thats no error in console

**Comment by MindOnFire93** [comment]
idk why really, anybody know how to fix?

**Comment by sfxcustoms** [comment]
Hi, i have the same problem can you tell me your version of:

Framework ESX:
Artifact Version:
Game DLC Level:

**Comment by nurrifqialhusaini** [comment]
Framework ESX: esx legacy
Artifact Version: 4394 
Game DLC Level: tunner shop

**Comment by sfxcustoms** [comment]
> Framework ESX: esx legacy Artifact Version: 4394 Game DLC Level: tunner shop

i have the same version, i am trying to change this hacking to other hacking

**Comment by nurrifqialhusaini** [comment]
> i have the same version, i am trying to change this hacking to other hacking

if u finish can u share with me ?

**Comment by MindOnFire93** [comment]
same version of previous, when worked some months ago, I try with the 1604, and latest 2189 artefact 4394 extended v 1.1.0 , my friend have the latest es_exnteded, and the ssame, when click on computer icons nothing happen, all other work normally.

**Comment by Kaekis** [comment]
I am having the same problem, when I enter the hacking game with the computer, when I click on the icons nothing happens, nor does it let me close the computer when I press the close icon, any solution to the problem? does anyone know what happened?

**Comment by MindOnFire93** [comment]
Yeah, same, i tryied to change server build, to change es_extended build, to roll back to backup when i secure all work fine, but nothing.

**Comment by utkuali** [comment]
fixed with https://github.com/utkuali/pacificheist-ESX-/commit/74144467ffb91b16aab0e7847525f32107d3060c

**Comment by MindOnFire93** [comment]
Big man! Thanks!
