### ISSUE TITLE
doors not closing

### ISSUE THREAD

**Issue by ShadowOfVoid** [utkuali/pacificheist-ESX-#8]
Hi , thanks for the great work , but sometimes doors dont close at all ! the word ( start loud bank heist )  will show but the doors are all open and you can go inside , i guess forcing the doors in a loop when some one is near the doors fix the issue , anyway , if you can fix this i will appreciate .

**Comment by utkuali** [comment]
Does this issue happen after robbing the bank or before ?

**Comment by ShadowOfVoid** [comment]
when i tested it was before robbing the bank , i will try to reproduce the bug and see if its fixed after the update

**Comment by utkuali** [comment]
@ShadowOfVoid so have you tested it ?

**Comment by ShadowOfVoid** [comment]
im truly sorry for the late respond , no unfortunately after a successfully rob , the doors will NOT close , and its not freezed.

**Comment by utkuali** [comment]
doors stay open for a long time intentionally, so that players inside won't be locked. Press E option will pop up before door locks however they won't be able to rob the bank because of the cooldown. So in the end when the cooldown ends doors will be locked no matter what.

**Comment by ShadowOfVoid** [comment]
thats the issue i guess , i set the cooldown on 100sec , and now the first door says ( [E] START loud bank heist ) but the doors are still open .

**Comment by ShadowOfVoid** [comment]
did you manage to check and fix the problem ?

**Comment by utkuali** [comment]
there is no issue read the above comment..

**Comment by withoutchiu** [comment]
Hi,

The door after 2nd hacking doesn't open. Do you know any leads?

Thanks!
